[versions]

file = "0.6.0"
java = "17"
kotlin = "2.3.0"
agp = "9.0.0"
maven-publish = "0.36.0"
io = "0.8.2"
kompress = "1.3.1"
datetime = "0.6.1"

[libraries]
file = { module = "io.matthewnelson.kmp-file:file", version.ref = "file" }
kotlinx-io = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "io" }
kompress-core = { module = "dev.karmakrafts.kompress:kompress-core", version.ref = "kompress" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "datetime" }

[plugins]

multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
android-kmp-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
android-application = { id = "com.android.application", version.ref = "agp" }
